export const REPOS_REQUEST = 'REPOS_REQUEST';
export const REPOS_SUCCESS = 'REPOS_SUCCESS';

export const REPOS_SEARCH_REQUEST = 'REPOS_SEARCH_REQUEST';
export const REPOS_SEARCH_SUCCESS = 'REPOS_SEARCH_SUCCESS';
export const REPOS_SEARCH_CLEAR = 'REPOS_SEARCH_CLEAR';
